# Generated by Django 3.1.4 on 2020-12-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=160)),
                ('invite_code', models.CharField(max_length=20, unique=True)),
                ('slug', models.CharField(max_length=130)),
                ('name', models.CharField(max_length=140)),
            ],
        ),
    ]
